DestravaLeitura/DestravaLeitura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepageApp.urls")),
    path("livros/", include("livros.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DestravaLeitura/homepageApp/urls.py
from django.urls import path
from homepageApp import views

app_name = "homepageApp"

urlpatterns =[
    path("", views.homepage, name="homepage"),
    path("sobre/", views.sobre, name="sobre")
]

DestravaLeitura/livros/urls.py
from django.urls import path
from livros import views

app_name = "livros"

urlpatterns =[
    path("", views.livros, name="livros"),
]

DestravaLeitura/homepageApp/models.py
from django.db import models

# Create your models here.

DestravaLeitura/livros/models.py
from django.db import models

# Create your models here.
class LivroInfo(models.Model):

    nome = models.CharField(max_length=264)
    autor = models.CharField(max_length=264)
    genero = models.CharField(max_length=264)
    xerox = models.CharField(max_length=264)
    emprestado = models.CharField(max_length=264)
    foto = models.ImageField(null=True, blank=True, upload_to="images/")
    
    def foto_url(self):
        if self.foto:
            return self.foto.url
        else:
            return '/static/images/book.jpg'

    

DestravaLeitura/homepageApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Ola")

def homepage(request):
    return render(request, "homepageApp/homepage.html")

def sobre(request):
    return render(request, "homepageApp/sobre.html")

DestravaLeitura/livros/views.py
from django.shortcuts import render
from .models import LivroInfo

# Create your views here.
def livros(request):
    qs = LivroInfo.objects.order_by("nome")
    name_query = request.GET.get("bookname")

    if name_query != "" and name_query is not None:
        qs = qs.filter(nome__icontains = name_query)

    return render(request, "livros/livros.html", {"livros": qs})

DestravaLeitura/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Destrava Leitura</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Zilla+Slab:wght@500&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <div class="navbar">
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <span class="navbar-brand" href="#">Destrava Leitura</span>
        <button class="navbar-toggler" class="btn btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepageApp:homepage' %}">Homepage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'livros:livros' %}">Livros</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepageApp:sobre' %}">Sobre</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <nav class="navbar navbar-expand-sm">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="https://www.instagram.com/destravaleitura/"><img src="../../static/images/Instagram.png" width="42" height="36"></a>
        </li>
      </ul>
    </nav>
  </div>
    

      <div class="container" id="content">

        {% block body_block %} 
        <!--Unique content of each page-->
        {% endblock %}

      </div>


</body>
</html>

DestravaLeitura/templates/homepageApp/homepage.html
{% extends 'base.html' %}
{% block body_block %}

<h1>Bem Vindo!</h1>

<h2>Vá para a seção <span id="destaque">Livros</span> para conferir as obras que nossa estante abriga.</h2>
<h2>Vá para a seção <span id="destaque">Sobre</span> para conferir mais detalhes do nosso projeto.</h2>
<h2>Clique no símbolo 
    <img src="../../static/images/Instagram.png" width="42" height="36"> no canto superior direito na 
    barra de navegação para ir ao nosso Instagram.   
</h2>
    
{% endblock %}

DestravaLeitura/templates/homepageApp/sobre.html
{% extends 'base.html' %}
{% block body_block %}

<h1>Olá!</h1>
<h2>Este é um projeto dos alunos Gabriela, Jordana, Maria Cecília, Pedro e Rayssa do Colégio BCLeme
    que busca incentivar a prática da leitura em nossa escola.</h2>
<h4>Buscamos fazer isso através da manutenção de uma estante literária, a qual usamos de meio para que
    os alunos possam trocar livros de casa por novos ou até mesmo comprar os livros de nossa estante. 
</h4>
<h4>Além da manutenção deste site, utilizamos nosso perfil do Instagram @destravaleitura para divulgar o projeto 
    e informar novidades para o público. 
</h4>

{% endblock %}

DestravaLeitura/templates/livros/livros.html
{% extends 'base.html' %}
{% block body_block %}
<nav class="navbar-nav ml-auto">
    <div class="container-fluid">
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Livro" aria-label="Search" name="bookname">
            <button class="btn btn-lg btn-light" type="submit">Buscar</button>
        </form>
        <ul id="book-list">
            {% for book in livros %}
            <ol id="book-item">
                <img id="book-image" src="{{ book.foto_url }}" alt="{{ book.nome }}" width="225" height="325">
                <div class="book-info">
                    <p>Nome: {{ book.nome }}</p>
                    <p>Autor(a): {{ book.autor }}</p>
                    <p>Gênero: {{ book.genero }}</p>
                    <p>Xerocado: {{ book.xerox }}</p>
                    <p>Status: {{ book.emprestado }}</p>
                </div>
            </ol>
            {% endfor %}
        </ul>
    </div>
</nav>
{%  endblock %}